name: bbapp
description: "Flutter basketball app for BETCLIC ELITE league"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  
  # Navigation
  auto_route: ^7.9.2
  
  # HTTP requests
  http: ^1.2.0
  dio: ^5.4.0
  
  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Error handling
  dartz: ^0.10.1
  
  # Image handling
  cached_network_image: ^3.3.1
  
  # Date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code generation
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  
  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/